/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestorAlmacenes.h"


void
supermercado_1(char *host)
{
	CLIENT *clnt;
	TDatosAlmacen  *result_1;
	int  datosalmacen_1_arg;
	int  *result_2;
	int  nproductos_1_arg;
	int  *result_3;
	TDatosAlmacen  crearalmacen_1_arg;
	int  *result_4;
	char  abriralmacen_1_arg;
	bool_t  *result_5;
	int  guardaralmacen_1_arg;
	bool_t  *result_6;
	int  cerraralmacen_1_arg;
	bool_t  *result_7;
	int  almacenabierto_1_arg;
	int  *result_8;
	TBusProd  buscaproducto_1_arg;
	TProducto  *result_9;
	TObtProd  obtenerproducto_1_arg;
	bool_t  *result_10;
	TActProd  anadirproducto_1_arg;
	bool_t  *result_11;
	TActProd  actualizarproducto_1_arg;
	bool_t  *result_12;
	TBusProd  eliminarproducto_1_arg;
	TProducto  *result_13;
	TOperacion  operacion_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUPERMERCADO, SUPERMERCADO_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = datosalmacen_1(&datosalmacen_1_arg, clnt);
	if (result_1 == (TDatosAlmacen *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = nproductos_1(&nproductos_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = crearalmacen_1(&crearalmacen_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = abriralmacen_1(&abriralmacen_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = guardaralmacen_1(&guardaralmacen_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = cerraralmacen_1(&cerraralmacen_1_arg, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = almacenabierto_1(&almacenabierto_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = buscaproducto_1(&buscaproducto_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = obtenerproducto_1(&obtenerproducto_1_arg, clnt);
	if (result_9 == (TProducto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = anadirproducto_1(&anadirproducto_1_arg, clnt);
	if (result_10 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = actualizarproducto_1(&actualizarproducto_1_arg, clnt);
	if (result_11 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = eliminarproducto_1(&eliminarproducto_1_arg, clnt);
	if (result_12 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = operacion_1(&operacion_1_arg, clnt);
	if (result_13 == (TProducto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	supermercado_1 (host);
exit (0);
}
