/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestorAlmacenes.h"

TDatosAlmacen *
datosalmacen_1_svc(int *argp, struct svc_req *rqstp)
{
	static TDatosAlmacen  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nproductos_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
crearalmacen_1_svc(TDatosAlmacen *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
abriralmacen_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
guardaralmacen_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
cerraralmacen_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
almacenabierto_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
buscaproducto_1_svc(TBusProd *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TProducto *
obtenerproducto_1_svc(TObtProd *argp, struct svc_req *rqstp)
{
	static TProducto  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
anadirproducto_1_svc(TActProd *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
actualizarproducto_1_svc(TActProd *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
eliminarproducto_1_svc(TBusProd *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TProducto *
operacion_1_svc(TOperacion *argp, struct svc_req *rqstp)
{
	static TProducto  result;

	/*
	 * insert server code here
	 */

	return &result;
}
