/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestorAlmacenes.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
supermercado_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int datosalmacen_1_arg;
		int nproductos_1_arg;
		TDatosAlmacen crearalmacen_1_arg;
		Cadena abriralmacen_1_arg;
		int guardaralmacen_1_arg;
		int cerraralmacen_1_arg;
		int almacenabierto_1_arg;
		TBusProd buscaproducto_1_arg;
		TObtProd obtenerproducto_1_arg;
		TActProd anadirproducto_1_arg;
		TActProd actualizarproducto_1_arg;
		TBusProd eliminarproducto_1_arg;
		TOperacion operacion_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DatosAlmacen:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_TDatosAlmacen;
		local = (char *(*)(char *, struct svc_req *)) datosalmacen_1_svc;
		break;

	case NProductos:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nproductos_1_svc;
		break;

	case CrearAlmacen:
		_xdr_argument = (xdrproc_t) xdr_TDatosAlmacen;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) crearalmacen_1_svc;
		break;

	case AbrirAlmacen:
		_xdr_argument = (xdrproc_t) xdr_Cadena;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) abriralmacen_1_svc;
		break;

	case GuardarAlmacen:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) guardaralmacen_1_svc;
		break;

	case CerrarAlmacen:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) cerraralmacen_1_svc;
		break;

	case AlmacenAbierto:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) almacenabierto_1_svc;
		break;

	case BuscaProducto:
		_xdr_argument = (xdrproc_t) xdr_TBusProd;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) buscaproducto_1_svc;
		break;

	case ObtenerProducto:
		_xdr_argument = (xdrproc_t) xdr_TObtProd;
		_xdr_result = (xdrproc_t) xdr_TProducto;
		local = (char *(*)(char *, struct svc_req *)) obtenerproducto_1_svc;
		break;

	case AnadirProducto:
		_xdr_argument = (xdrproc_t) xdr_TActProd;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) anadirproducto_1_svc;
		break;

	case ActualizarProducto:
		_xdr_argument = (xdrproc_t) xdr_TActProd;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) actualizarproducto_1_svc;
		break;

	case EliminarProducto:
		_xdr_argument = (xdrproc_t) xdr_TBusProd;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) eliminarproducto_1_svc;
		break;

	case operacion:
		_xdr_argument = (xdrproc_t) xdr_TOperacion;
		_xdr_result = (xdrproc_t) xdr_TProducto;
		local = (char *(*)(char *, struct svc_req *)) operacion_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SUPERMERCADO, SUPERMERCADO_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SUPERMERCADO, SUPERMERCADO_VER, supermercado_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUPERMERCADO, SUPERMERCADO_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SUPERMERCADO, SUPERMERCADO_VER, supermercado_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SUPERMERCADO, SUPERMERCADO_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
