/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTORALMACENES_H_RPCGEN
#define _GESTORALMACENES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char Cadena[90];

struct TFecha {
	int Dia;
	int Mes;
	int Anyo;
};
typedef struct TFecha TFecha;

struct TProducto {
	Cadena CodProd;
	int Cantidad;
	Cadena NombreProd;
	float Precio;
	Cadena Descripcion;
	struct TFecha Caducidad;
};
typedef struct TProducto TProducto;

struct TDatosAlmacen {
	Cadena Nombre;
	Cadena Direccion;
	Cadena Fichero;
};
typedef struct TDatosAlmacen TDatosAlmacen;

struct TBusProd {
	int Almacen;
	Cadena CodProducto;
};
typedef struct TBusProd TBusProd;

struct TObtProd {
	int Almacen;
	int PosProducto;
};
typedef struct TObtProd TObtProd;

struct TActProd {
	int Almacen;
	struct TProducto Producto;
};
typedef struct TActProd TActProd;

struct TOperacion {
	int p1;
	Cadena p2;
	float p3;
	float p4;
};
typedef struct TOperacion TOperacion;

#define SUPERMERCADO 0x30000001
#define SUPERMERCADO_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define DatosAlmacen 1
extern  TDatosAlmacen * datosalmacen_1(int *, CLIENT *);
extern  TDatosAlmacen * datosalmacen_1_svc(int *, struct svc_req *);
#define NProductos 2
extern  int * nproductos_1(int *, CLIENT *);
extern  int * nproductos_1_svc(int *, struct svc_req *);
#define CrearAlmacen 3
extern  int * crearalmacen_1(TDatosAlmacen *, CLIENT *);
extern  int * crearalmacen_1_svc(TDatosAlmacen *, struct svc_req *);
#define AbrirAlmacen 4
extern  int * abriralmacen_1(char *, CLIENT *);
extern  int * abriralmacen_1_svc(char *, struct svc_req *);
#define GuardarAlmacen 5
extern  bool_t * guardaralmacen_1(int *, CLIENT *);
extern  bool_t * guardaralmacen_1_svc(int *, struct svc_req *);
#define CerrarAlmacen 6
extern  bool_t * cerraralmacen_1(int *, CLIENT *);
extern  bool_t * cerraralmacen_1_svc(int *, struct svc_req *);
#define AlmacenAbierto 7
extern  bool_t * almacenabierto_1(int *, CLIENT *);
extern  bool_t * almacenabierto_1_svc(int *, struct svc_req *);
#define BuscaProducto 8
extern  int * buscaproducto_1(TBusProd *, CLIENT *);
extern  int * buscaproducto_1_svc(TBusProd *, struct svc_req *);
#define ObtenerProducto 9
extern  TProducto * obtenerproducto_1(TObtProd *, CLIENT *);
extern  TProducto * obtenerproducto_1_svc(TObtProd *, struct svc_req *);
#define AnadirProducto 10
extern  bool_t * anadirproducto_1(TActProd *, CLIENT *);
extern  bool_t * anadirproducto_1_svc(TActProd *, struct svc_req *);
#define ActualizarProducto 11
extern  bool_t * actualizarproducto_1(TActProd *, CLIENT *);
extern  bool_t * actualizarproducto_1_svc(TActProd *, struct svc_req *);
#define EliminarProducto 12
extern  bool_t * eliminarproducto_1(TBusProd *, CLIENT *);
extern  bool_t * eliminarproducto_1_svc(TBusProd *, struct svc_req *);
#define operacion 13
extern  TProducto * operacion_1(TOperacion *, CLIENT *);
extern  TProducto * operacion_1_svc(TOperacion *, struct svc_req *);
extern int supermercado_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DatosAlmacen 1
extern  TDatosAlmacen * datosalmacen_1();
extern  TDatosAlmacen * datosalmacen_1_svc();
#define NProductos 2
extern  int * nproductos_1();
extern  int * nproductos_1_svc();
#define CrearAlmacen 3
extern  int * crearalmacen_1();
extern  int * crearalmacen_1_svc();
#define AbrirAlmacen 4
extern  int * abriralmacen_1();
extern  int * abriralmacen_1_svc();
#define GuardarAlmacen 5
extern  bool_t * guardaralmacen_1();
extern  bool_t * guardaralmacen_1_svc();
#define CerrarAlmacen 6
extern  bool_t * cerraralmacen_1();
extern  bool_t * cerraralmacen_1_svc();
#define AlmacenAbierto 7
extern  bool_t * almacenabierto_1();
extern  bool_t * almacenabierto_1_svc();
#define BuscaProducto 8
extern  int * buscaproducto_1();
extern  int * buscaproducto_1_svc();
#define ObtenerProducto 9
extern  TProducto * obtenerproducto_1();
extern  TProducto * obtenerproducto_1_svc();
#define AnadirProducto 10
extern  bool_t * anadirproducto_1();
extern  bool_t * anadirproducto_1_svc();
#define ActualizarProducto 11
extern  bool_t * actualizarproducto_1();
extern  bool_t * actualizarproducto_1_svc();
#define EliminarProducto 12
extern  bool_t * eliminarproducto_1();
extern  bool_t * eliminarproducto_1_svc();
#define operacion 13
extern  TProducto * operacion_1();
extern  TProducto * operacion_1_svc();
extern int supermercado_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Cadena (XDR *, Cadena);
extern  bool_t xdr_TFecha (XDR *, TFecha*);
extern  bool_t xdr_TProducto (XDR *, TProducto*);
extern  bool_t xdr_TDatosAlmacen (XDR *, TDatosAlmacen*);
extern  bool_t xdr_TBusProd (XDR *, TBusProd*);
extern  bool_t xdr_TObtProd (XDR *, TObtProd*);
extern  bool_t xdr_TActProd (XDR *, TActProd*);
extern  bool_t xdr_TOperacion (XDR *, TOperacion*);

#else /* K&R C */
extern bool_t xdr_Cadena ();
extern bool_t xdr_TFecha ();
extern bool_t xdr_TProducto ();
extern bool_t xdr_TDatosAlmacen ();
extern bool_t xdr_TBusProd ();
extern bool_t xdr_TObtProd ();
extern bool_t xdr_TActProd ();
extern bool_t xdr_TOperacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTORALMACENES_H_RPCGEN */
